sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: iHwgB3NVoY25adlkn360hzLI2RIuZdDUmwr26qYU0wsOvgh7z1XuQ1chSw/pH4D2KTJ1HGTwd2S3UTiH3VfDc2t6lNpGGQmTaCb/1/dM8k401mS1p0JrCRQRhIniao/UPuzg8O2FrqpCFOv8J10aeib+K1+Ffc71Umw0kYoIpfX2xt6vYpkNvQucOK3YOwAna4U77j985l8zGJ8YY+sFHt9D1WWMMb0kBIIsaveH12FOFnQjvwZM1NTgCeo4X61Grelm+WLXBuVYRrPOhPOcFcj8TaaqY4QMh1IsR+IiuqR8f56e9SeiwMtsnccfLkV2H0PnTZGlCkT196upfXJWqaGtGna+v3l4W8HzlyglhJlSlBrXFmXr7+Zs2YKMrY4/O6CyuX1RhboQX6oOwZzB06pvpAHic8IMG0brEmibZ/CAk1Qz966x/i9Jo8UcEiaLvB0QVaJEU/UHn8d7Iln/TcQpyq2yRsNpgCDPmCrcZGkNw7GshuMlCVpH2gPBgdWVftDbDSw8aeGGTrde1xHdblNcrGQeR3x7UXdvN7LFNXepnocAAUYZTsKghIAA1IgpCDXys5WF4sYnbryY3Yx+hB4ufZOXy3zbhMeraoouTiNjS+oJr74Jc1lQgyLI7E3HLUSqXkL/PYrQZjWTzPMgbrrgRoHc4GBAkxChdqAUoXU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Man-Eaters-of-Tsavo-and-Other-East-African-Adventures_3810
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy